### PR TITLE
[REF] simplify adding new chains

### PR DESCRIPTION
**Pull request by gabrielbazan7**
- support `chain` in currency utils
- add `chain` to contacts
- handle new token rates format -> (usdc_e, busd_e)
- handle differents coingecko blockchain networks
- adding `badgeImg` property to all erc20 tokens and `chain` to all wallets obj
- REF supported coins and tokens constants to better handle new evm chains
- refresh wallet obj in transform function to make sure `chain` (or other properties) is not missing
- use `chain`, `network` and `currencyAbbreviation` instead of `credentials.chain/network/coin`
- handle `chain` in incomingData
- `chain` and `currencyAbbreviation` always in lowercase
- add chain suffix to token names

### CODE REVIEW

**Review by Gamboster — APPROVED** [review]
ACK. Huge work 👏🏼

**Review by cmgustavo — DISMISSED** [review]
LGTM! Great work! 🚀

**Comment by lanchana** [comment]
Global select Send is not working

**Review by Gamboster — DISMISSED** [review]

**Review by cmgustavo — APPROVED** [review]
LGTM!

**Review by cmgustavo — APPROVED** [review]

**Pull request merged**
