### PR TITLE
[FEAT] app migration

### PR DESCRIPTION
**Pull request by JohnathanWhite**
- [x] Base migration setup
- [x] UI Flow changes -> intro is only shown if migration else onboarding start
- [x] Keys (encrypted, non encrypted)
- [x] App identity
- [x] Address book
- [x] BitPay id
- [x] Migration failure modal
- [ ] Gift cards
- [x] Coinbase
- [x] Settings

### CODE REVIEW

**Comment by JohnathanWhite** [comment]
working on the rates and balance issue

**Comment by JohnathanWhite** [comment]
best way to test on IOS -> 

1. install old app and setup address book, bp id, keys, etc
2. in new app -> store/index.ts -> enable persistor.purge so that the store is cleared on every refresh
3. In xcode make sure bundle id is com.bitpay.wallet and install new app. Currently we are not clearing Cordova storage so every refresh will run migration.

**Comment by JohnathanWhite** [comment]
Screen Shot 2022-05-26 at 12 36 30 PM

will have to make the above change when testing coinbase migration

**Review by gabrielbazan7 — APPROVED** [review]
ACK!

**Pull request merged**
