### PR TITLE
Feat: Moonpay integration

### PR DESCRIPTION
**Pull request by Gamboster**
This PR needs: https://github.com/bitpay/bitcore/pull/3483/files

`yarn install`

Tip: The Moonpay sandbox environment only supports testnet addresses. Attempting to use livenet wallets in this environment will result in an address validation error on the checkout website.

Test cards:
```
Test card numbers for 3D Secure transactions 
Visa
4000 0209 5159 5032 
12/2022 
123

 Test card numbers for declined transactions
  Visa 
  4000 3198 7280 7223 
  12/2022 
  123```

### CODE REVIEW

**Review by rastajpa — DISMISSED** [review]
LGTM! (Tested with different currencies and payment methods)

**Review by rastajpa — APPROVED** [review]
good catch

**Review by cmgustavo — DISMISSED** [review]
ACK! 💪🏼

**Review by cmgustavo — APPROVED** [review]
LGTM!

**Review by rastajpa — APPROVED** [review]

**Review by cnguyen812 — CHANGES_REQUESTED** [review]

**Review by JohnathanWhite — APPROVED** [review]

**Pull request merged**
