### PR TITLE
[FIX] wallet transform (chain migration)

### PR DESCRIPTION
**Pull request by gabrielbazan7**

### CODE REVIEW

**Review by cmgustavo — APPROVED** [review]
LGTM!

**Comment by JohnathanWhite** [comment]
can you remove the unused imports?

**Comment by JohnathanWhite** [comment]
Screen Shot 2022-10-24 at 9 06 44 PM

**Comment by gabrielbazan7** [comment]
Done

**Review by JohnathanWhite — APPROVED** [review]

**Pull request merged**
