### PR TITLE
Feat/refactor amount screen components

### PR DESCRIPTION
**Pull request by cnguyen812**
Issue: `Amount` screen component had to dynamically handle 2 argument lists depending on usage as a screen or standalone component.

Refactored it into a standalone component with explicit event handler props, also created an AmountModal component to replace the duplicates for buy/swap/coinbase

### CODE REVIEW

**Comment by gabrielbazan7** [comment]
You can also delete /navigation/wallet/components/amountModal.tsx file and use the shared component for the select inputs feature

**Review by gabrielbazan7 — CHANGES_REQUESTED** [review]
Currently not working when running the app

**Comment by cnguyen812** [comment]
Other amountModal replaced, merge conflicts fixed, ready for re-review

**Review by gabrielbazan7 — DISMISSED** [review]
ACK!

**Review by Gamboster — APPROVED** [review]
ACK. Great job!

**Comment by JohnathanWhite** [comment]
merge conflicts

**Comment by cmgustavo** [comment]
Needs rebase: 
```
* What went wrong:
Execution failed for task ':app:installDebug'.
> java.util.concurrent.ExecutionException: com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_FAILED_VERSION_DOWNGRADE
```

**Review by gabrielbazan7 — APPROVED** [review]

**Pull request merged**
