### PR TITLE
[REF] rename from pax to usdp

### PR DESCRIPTION
**Pull request by gabrielbazan7**
Fixes: 

- paying invoices is not possible right now

- show correct name and symbol when creating a wallet

iPhone_12

- Rate not found for currency: usdp

- possible duplicated key error if wrong pax wallet is created

### CODE REVIEW

**Comment by JohnathanWhite** [comment]
need to rebase

**Review by cmgustavo — DISMISSED** [review]
ACK! 💪🏼

**Review by rastajpa — APPROVED** [review]
LGTM, nice work!

**Review by cmgustavo — APPROVED** [review]
LGTM!

**Pull request merged**
