### PR TITLE
Feat/one link setup

### PR DESCRIPTION
**Pull request by cnguyen812**
This PR configures the app to recognize `onelink.me` links and adds new handlers for buy crypto, create wallet, card activation, and card referral, as well as defers any deferred deeplink until 1) app data has initialized 2) navigator is ready and 3) has completed onboarding.

Testing:
Use this link: https://bitpay.onelink.me/Cenw/thawwukx or create/edit your own in the AppsFlyer dashboard.

If app is installed, it should take you to the correct screen like a normal deeplink.
If app not installed, it should 1) redirect to app store 2) now install the app from your local 3) app should handle the deferred deeplink after onboarding is complete.

The new deeplinks are: `buy-crypto`, `wallet/create`, `card/activate`, and `card/referral`.

### CODE REVIEW

**Comment by cmgustavo** [comment]
Needs rebase

**Comment by cmgustavo** [comment]
For some reason, redirect to specific page for any deep link doesn't work. Try a simple bitcoin uri: `bitcoin:mq8Hc2XwYqXw4sPTc8i7wPx9iJzTFTBWbQ`

**Comment by cnguyen812** [comment]
@cmgustavo Merged a fix for deeplinks, can you try now?

**Review by JohnathanWhite — APPROVED** [review]
ACK! 🚀 💯

**Pull request merged**
