### PR TITLE
WIP [REF] account selector - highlight selected

### PR DESCRIPTION
**Pull request by gabrielbazan7**

### CODE REVIEW

**Review by cmgustavo — DISMISSED** [review]
ACK!

**Review by cmgustavo — APPROVED** [review]

**Review by cmgustavo — APPROVED** [review]

**Comment by JohnathanWhite** [comment]
still have issue with tapping on the pill

**Comment by JohnathanWhite** [comment]
receiveAddress is working now! nice job!

**Comment by cmgustavo** [comment]
It's working for me: 

https://github.com/bitpay/bitpay-app/assets/237435/e83a7e3d-ccec-40ff-94a3-1da06b6ea914

**Review by JohnathanWhite — APPROVED** [review]

**Pull request merged**
