### PR TITLE
[REF] move to native stack navigation

### PR DESCRIPTION
**Pull request by gabrielbazan7**

### CODE REVIEW

**Comment by Gamboster** [comment]
I've been testing the navigation a lot and it seems to work well. The only issue I detect is that the `TransactMenu` doesn't close after select an option. The app freezes.

**Comment by gabrielbazan7** [comment]
@Gamboster fixed. Thanks for reviewing

**Review by Gamboster — DISMISSED** [review]
LGTM 
It seems to be working correctly, I tested everything I could in the iOS simulator. The issue I mentioned previously was fixed.

**Comment by gabrielbazan7** [comment]
https://github.com/bitpay/bitpay-app/pull/1005

**Pull request closed without merging**
